// <auto-generated />
using System;
using HappyFitness.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappyFitness.Infrastructure.Migrations
{
    [DbContext(typeof(HappyFitnessDbContext))]
    [Migration("20250718094916_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HappyFitness.Domain.Common.BodyPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BodyParts");
                });

            modelBuilder.Entity("HappyFitness.Domain.Common.ExerciseDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BodyPartId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BodyPartId");

                    b.ToTable("ExerciseDefinitions");
                });

            modelBuilder.Entity("HappyFitness.Domain.Common.FoodProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<float>("CaloriesPer100g")
                        .HasColumnType("float");

                    b.Property<float>("CarbsPer100g")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("FatPer100g")
                        .HasColumnType("float");

                    b.Property<Guid>("FoodSourceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<float>("ProteinPer100g")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FoodSourceId");

                    b.ToTable("FoodProducts");
                });

            modelBuilder.Entity("HappyFitness.Domain.Common.FoodSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FoodSources");
                });

            modelBuilder.Entity("HappyFitness.Domain.Common.MealType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MealTypes");
                });

            modelBuilder.Entity("HappyFitness.Domain.Meals.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MealTypeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("HappyFitness.Domain.Meals.MealEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FoodProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MealId")
                        .HasColumnType("char(36)");

                    b.Property<float>("WeightInGrams")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FoodProductId");

                    b.HasIndex("MealId");

                    b.ToTable("MealEntries");
                });

            modelBuilder.Entity("HappyFitness.Domain.Users.PlanExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ExerciseDefinitionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("TargetRepsMax")
                        .HasColumnType("int");

                    b.Property<int>("TargetRepsMin")
                        .HasColumnType("int");

                    b.Property<int>("TargetSets")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkoutPlanId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseDefinitionId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("PlanExercises");
                });

            modelBuilder.Entity("HappyFitness.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HappyFitness.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("DailyCalorieGoal")
                        .HasColumnType("float");

                    b.Property<float>("DailyCarbsGoal")
                        .HasColumnType("float");

                    b.Property<float>("DailyFatGoal")
                        .HasColumnType("float");

                    b.Property<float>("DailyProteinGoal")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("HappyFitness.Domain.Users.WorkoutPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("HappyFitness.Domain.Workouts.PerformedExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ExerciseDefinitionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseDefinitionId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("PerformedExercises");
                });

            modelBuilder.Entity("HappyFitness.Domain.Workouts.PerformedSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PerformedExerciseId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<float>("WeightInKgs")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PerformedExerciseId");

                    b.ToTable("PerformedSets");
                });

            modelBuilder.Entity("HappyFitness.Domain.Workouts.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("HappyFitness.Domain.Common.ExerciseDefinition", b =>
                {
                    b.HasOne("HappyFitness.Domain.Common.BodyPart", "BodyPart")
                        .WithMany()
                        .HasForeignKey("BodyPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyPart");
                });

            modelBuilder.Entity("HappyFitness.Domain.Common.FoodProduct", b =>
                {
                    b.HasOne("HappyFitness.Domain.Common.FoodSource", "FoodSource")
                        .WithMany()
                        .HasForeignKey("FoodSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodSource");
                });

            modelBuilder.Entity("HappyFitness.Domain.Meals.Meal", b =>
                {
                    b.HasOne("HappyFitness.Domain.Common.MealType", "MealType")
                        .WithMany()
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HappyFitness.Domain.Users.User", "User")
                        .WithMany("Meals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HappyFitness.Domain.Meals.MealEntry", b =>
                {
                    b.HasOne("HappyFitness.Domain.Common.FoodProduct", "FoodProduct")
                        .WithMany()
                        .HasForeignKey("FoodProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HappyFitness.Domain.Meals.Meal", "Meal")
                        .WithMany("MealEntries")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodProduct");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("HappyFitness.Domain.Users.PlanExercise", b =>
                {
                    b.HasOne("HappyFitness.Domain.Common.ExerciseDefinition", "ExerciseDefinition")
                        .WithMany()
                        .HasForeignKey("ExerciseDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HappyFitness.Domain.Users.WorkoutPlan", "WorkoutPlan")
                        .WithMany("PlanExercises")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseDefinition");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("HappyFitness.Domain.Users.UserProfile", b =>
                {
                    b.HasOne("HappyFitness.Domain.Users.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("HappyFitness.Domain.Users.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HappyFitness.Domain.Users.WorkoutPlan", b =>
                {
                    b.HasOne("HappyFitness.Domain.Users.User", "User")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HappyFitness.Domain.Workouts.PerformedExercise", b =>
                {
                    b.HasOne("HappyFitness.Domain.Common.ExerciseDefinition", "ExerciseDefinition")
                        .WithMany()
                        .HasForeignKey("ExerciseDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HappyFitness.Domain.Workouts.WorkoutSession", "WorkoutSession")
                        .WithMany("PerformedExercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseDefinition");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("HappyFitness.Domain.Workouts.PerformedSet", b =>
                {
                    b.HasOne("HappyFitness.Domain.Workouts.PerformedExercise", "PerformedExercise")
                        .WithMany("PerformedSets")
                        .HasForeignKey("PerformedExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformedExercise");
                });

            modelBuilder.Entity("HappyFitness.Domain.Workouts.WorkoutSession", b =>
                {
                    b.HasOne("HappyFitness.Domain.Users.User", "User")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HappyFitness.Domain.Meals.Meal", b =>
                {
                    b.Navigation("MealEntries");
                });

            modelBuilder.Entity("HappyFitness.Domain.Users.User", b =>
                {
                    b.Navigation("Meals");

                    b.Navigation("Profile");

                    b.Navigation("WorkoutPlans");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("HappyFitness.Domain.Users.WorkoutPlan", b =>
                {
                    b.Navigation("PlanExercises");
                });

            modelBuilder.Entity("HappyFitness.Domain.Workouts.PerformedExercise", b =>
                {
                    b.Navigation("PerformedSets");
                });

            modelBuilder.Entity("HappyFitness.Domain.Workouts.WorkoutSession", b =>
                {
                    b.Navigation("PerformedExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
